version: '2'

services:
  ss-redir_main:
    container_name: ss-redir_main
    image: lisnaz/shadowsocks-libev-redir:latest
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.18.0.2
    environment:
      - SS_REDIR_LISTEN_ADDR=<shadowsocks-libev redir's listening address>
      - SS_REDIR_LISTEN_PORT=<shadowsocks-libev redir's listening port>
      - SS_REDIR_TARGET_ADDR=<your shadowsocks-libev server's address>
      - SS_REDIR_TARGET_PORT=<your shadowsocks-libev server's port>
      - SS_PASSWORD=password

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
